/* Class-schedule tabs - owned by Claude, generated by schedule/sync_schedule.py.
   Adds a "Morning brief | Schedule" tab bar and a today/tomorrow strip to any page
   that includes <script src="/tabs.js" defer></script>. It never edits that page's
   files: everything is inserted in the browser, inside shadow DOM. */
(function () {
  if (window.__sdTabs) return;
  window.__sdTabs = true;
let SD = { days: [] }, DAYS = [], BY = {};
function setData(o) { SD = o; DAYS = o.days || []; BY = {}; DAYS.forEach(d => { BY[d.date] = d; }); }
const TYPES = {
  home:   { label: 'Student home',  short: 'Home',    cls: 't-home' },
  onsite: { label: 'Group on-site', short: 'On-site', cls: 't-onsite' },
  online: { label: 'Group online',  short: 'Online',  cls: 't-online' },
  other:  { label: 'Class',         short: 'Class',   cls: 't-other' }
};
const THAI = { Mon:'#FFD966', Tue:'#F4B6C2', Wed:'#93C47D', Thu:'#F6B26B', Fri:'#6FA8DC', Sat:'#B4A7D6', Sun:'#E06666' };
const DOW = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
const MON = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function todayBkk() { return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Bangkok' }).format(new Date()); }
function addDays(ds, n) { const p = ds.split('-').map(Number); return new Date(Date.UTC(p[0], p[1]-1, p[2]+n)).toISOString().slice(0,10); }
function parts(ds) { const p = ds.split('-').map(Number); const dt = new Date(Date.UTC(p[0], p[1]-1, p[2])); return { d: p[2], dow: DOW[dt.getUTCDay()], mon: MON[p[1]-1] }; }
function mins(t) { const p = t.split(':').map(Number); return p[0]*60 + p[1]; }
function f12(min) { min = ((min % 1440) + 1440) % 1440; let h = Math.floor(min/60); const m = min % 60; const ap = h >= 12 ? 'PM' : 'AM'; h = h % 12 || 12; return h + ':' + String(m).padStart(2,'0') + ' ' + ap; }
function summary(day) {
  const c = (day && day.classes) || [];
  if (!c.length) return null;
  const first = Math.min.apply(null, c.map(x => mins(x.start)));
  const fin = Math.max.apply(null, c.map(x => mins(x.end)));
  const hrs = c.reduce((a, x) => a + mins(x.end) - mins(x.start), 0) / 60;
  return { first: first, fin: fin, start: fin - 540, hrs: hrs };
}
function hrsLabel(h) { return (Math.round(h * 100) / 100) + ' h'; }
function chip(ds) { const p = parts(ds); return '<span class="sd-chip" style="background:' + THAI[p.dow] + '">' + p.dow + '</span>'; }
function dateLabel(ds) { const p = parts(ds); return p.dow + ' ' + p.d + ' ' + p.mon; }
function shortDate(ds) { const p = parts(ds); return p.d + ' ' + p.mon; }
function rng(a, b) { const x = f12(a), y = f12(b); return (x.slice(-2) === y.slice(-2) ? x.slice(0, -3) : x) + '–' + y; }
function classLine(c) {
  const t = TYPES[c.type] || TYPES.other;
  return '<li class="sd-cl"><span class="sd-tm">' + f12(mins(c.start)) + ' – ' + f12(mins(c.end)) +
    '</span><span class="sd-pill ' + t.cls + '">' + t.label + '</span><span class="sd-nm">' + esc(c.name) + '</span></li>';
}
function dayCard(ds, rel, today) {
  const day = BY[ds], s = summary(day);
  let h = '<section class="sd-day' + (ds === today ? ' is-today' : '') + '"><div class="sd-head">' + chip(ds) +
    '<span class="sd-date">' + shortDate(ds) + '</span>' + (rel ? '<span class="sd-rel">' + rel + '</span>' : '') + '</div>';
  if (!day) { return h + '<p class="sd-rest">Not in the schedule yet.</p></section>'; }
  if (!s) { return h + '<p class="sd-rest">Rest day – no classes.</p></section>'; }
  h += '<div class="sd-tiles"><div class="sd-tile alarm"><span>⏰ Start</span><b>' + f12(s.start) + '</b></div>' +
    '<div class="sd-tile"><span>First class</span><b>' + f12(s.first) + '</b></div>' +
    '<div class="sd-tile alarm"><span>⏰ Finish</span><b>' + f12(s.fin) + '</b></div></div><ul class="sd-list">' +
    day.classes.map(classLine).join('') + '</ul></section>';
  return h;
}
function miniRow(ds, today) {
  const day = BY[ds], s = summary(day);
  const cls = ds === today ? ' is-today' : '';
  if (!s) {
    return '<div class="sd-row is-rest' + cls + '">' + chip(ds) + '<div class="sd-main"><span class="sd-date">' + shortDate(ds) + '</span> <span class="sd-foot">· rest</span></div></div>';
  }
  const items = day.classes.map(c => { const t = TYPES[c.type] || TYPES.other;
    return '<li><span class="sd-mtm">' + rng(mins(c.start), mins(c.end)) + '</span><span class="sd-pill ' + t.cls + '">' + t.short + '</span><span class="sd-nm">' + esc(c.name) + '</span></li>'; }).join('');
  return '<div class="sd-row' + cls + '">' + chip(ds) + '<div class="sd-main"><span class="sd-date">' + shortDate(ds) +
    '</span><ul class="sd-mini">' + items + '</ul></div><div class="sd-side"><div><small>Start</small> <b>' + f12(s.start) + '</b></div><div><small>Finish</small> <b>' + f12(s.fin) + '</b></div></div></div>';
}
function mondayOf(ds) { const p = parts(ds); const back = (DOW.indexOf(p.dow) + 6) % 7; return addDays(ds, -back); }
function updatedLabel() {
  if (!SD.updated) return '';
  const p = SD.updated.slice(0, 10);
  return 'Schedule last changed ' + dateLabel(p);
}

  const CSS = `.sd{--sd-card:var(--card,#181b22);--sd-text:var(--text,#e8eaef);--sd-muted:var(--muted,#9aa3b2);--sd-accent:var(--accent,#f5c542);--sd-line:color-mix(in srgb,var(--sd-muted) 30%,transparent);color:var(--sd-text)}
.sd *{box-sizing:border-box}
.sd-day{background:var(--sd-card);border:1px solid var(--sd-line);border-radius:14px;padding:.9rem 1rem;margin:.7rem 0}
.sd-day.is-today{border-color:var(--sd-accent)}
.sd-head{display:flex;align-items:center;gap:.6rem;flex-wrap:wrap}
.sd-chip{font-weight:700;font-size:.78rem;padding:.2rem .6rem;border-radius:999px;color:#1a1d24;min-width:2.9rem;text-align:center}
.sd-date{font-weight:650}
.sd-rel{margin-left:auto;font-size:.72rem;letter-spacing:.05em;text-transform:uppercase;color:var(--sd-accent);font-weight:700}
.sd-tiles{display:grid;grid-template-columns:repeat(3,1fr);gap:.5rem;margin:.8rem 0 .5rem}
.sd-tile{background:color-mix(in srgb,var(--sd-muted) 12%,transparent);border-radius:10px;padding:.5rem .6rem;min-width:0}
.sd-tile b{display:block;font-size:1.02rem;white-space:nowrap}
.sd-tile span{font-size:.66rem;color:var(--sd-muted);text-transform:uppercase;letter-spacing:.04em}
.sd-tile.alarm{outline:2px solid var(--sd-accent);outline-offset:-2px}
.sd-list{list-style:none;margin:0;padding:0}
.sd-cl{display:flex;flex-wrap:wrap;align-items:center;gap:.25rem .6rem;padding:.5rem 0;border-top:1px solid var(--sd-line);font-size:.92rem}
.sd-tm{font-variant-numeric:tabular-nums;color:var(--sd-muted);min-width:11.2rem}
.sd-pill{font-size:.7rem;font-weight:700;padding:.12rem .55rem;border-radius:999px;color:#1a1d24;white-space:nowrap}
.t-home{background:#F9CB9C}.t-onsite{background:#9FC5E8}.t-online{background:#D9D2E9}.t-other{background:#d0d4db}
.sd-nm{min-width:0;overflow-wrap:anywhere}
.sd-rest{color:var(--sd-muted);margin:.55rem 0 .1rem;font-size:.92rem}
.sd-foot{color:var(--sd-muted);font-size:.8rem;margin:.6rem 0 0}
.sd-row{display:flex;gap:.7rem;align-items:flex-start;padding:.6rem .1rem;border-top:1px solid var(--sd-line)}
.sd-row.is-today{background:color-mix(in srgb,var(--sd-accent) 12%,transparent);border-radius:10px;padding-left:.5rem;padding-right:.5rem}
.sd-row.is-rest{opacity:.55;padding:.35rem .1rem}
.sd-row .sd-chip{margin-top:.1rem}
.sd-main{flex:1;min-width:0}
.sd-main .sd-date{font-size:.92rem}
.sd-mini{list-style:none;margin:.2rem 0 0;padding:0;font-size:.84rem;color:var(--sd-muted)}
.sd-mini li{margin:.3rem 0;display:flex;flex-wrap:wrap;align-items:center;gap:.15rem .1rem}
.sd-mtm{white-space:nowrap;font-variant-numeric:tabular-nums;margin-right:.2rem}
.sd-mini .sd-pill{font-size:.64rem;margin:0 .4rem}
.sd-side{text-align:right;font-size:.82rem;font-variant-numeric:tabular-nums;white-space:nowrap;line-height:1.5}
.sd-side small{color:var(--sd-muted);font-size:.66rem;text-transform:uppercase;letter-spacing:.04em;margin-right:.15rem}
.sd-week{margin:1.4rem 0 .2rem;display:flex;justify-content:space-between;align-items:baseline;font-size:.8rem;color:var(--sd-muted);text-transform:uppercase;letter-spacing:.05em;font-weight:650}
@media (max-width:30rem){.sd-tm{min-width:100%}}

.wrap{max-width:42rem;margin:0 auto;padding:.5rem 1.25rem}
.nav{background:var(--bg,#0f1115);border-bottom:1px solid var(--sd-line);font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
.nav .wrap{display:flex;gap:.5rem}
.tab{flex:1;text-align:center;padding:.6rem .8rem;border-radius:12px;text-decoration:none;font-weight:600;font-size:.95rem;color:var(--sd-text);border:1px solid var(--sd-line)}
.tab[aria-current="page"]{background:color-mix(in srgb,var(--sd-accent) 18%,transparent);border-color:var(--sd-accent)}
.strip{font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;font-size:.92rem}
.strip .wrap{padding-top:.9rem;padding-bottom:.2rem}
.sd-sd{display:flex;flex-wrap:wrap;align-items:center;gap:.3rem .6rem;margin-top:.55rem}
.sd-sd .sd-chip{font-size:.72rem;min-width:2.6rem}
.sd-times b{font-variant-numeric:tabular-nums}
.sd-rest-i{color:var(--sd-muted)}
.strip .sd-mini{margin:.15rem 0 0 .2rem}
.more{display:inline-block;margin-top:.7rem;color:var(--link,#7db4ff);font-size:.85rem}
`;
  const here = location.pathname.replace(/index\.html$/, '');
  function host(html, sticky) {
    const h = document.createElement('div');
    h.className = 'sd-host';
    if (sticky) h.style.cssText = 'position:sticky;top:0;z-index:50';
    const root = h.attachShadow({ mode: 'open' });
    root.innerHTML = '<style>' + CSS + '</style>' + html;
    return h;
  }
  function stripDay(ds, rel) {
    const day = BY[ds], s = summary(day);
    let h = '<div class="sd-sd">' + chip(ds) + '<span><b>' + rel + '</b> · ' + shortDate(ds) + '</span>';
    if (!day) h += '<span class="sd-rest-i">not in the schedule yet</span>';
    else if (!s) h += '<span class="sd-rest-i">Rest day</span>';
    else h += '<span class="sd-times">⏰ <b>' + f12(s.start) + '</b> start · ' + f12(s.first) + ' first class · ⏰ <b>' + f12(s.fin) + '</b> finish</span>';
    h += '</div>';
    if (s) h += '<ul class="sd-mini">' + day.classes.map(c => { const t = TYPES[c.type] || TYPES.other;
      return '<li><span class="sd-mtm">' + rng(mins(c.start), mins(c.end)) + '</span><span class="sd-pill ' + t.cls + '">' + t.short + '</span><span class="sd-nm">' + esc(c.name) + '</span></li>'; }).join('') + '</ul>';
    return h;
  }
  const nav = host('<div class="nav sd"><div class="wrap"><a class="tab" href="/"' + (here === '/' ? ' aria-current="page"' : '') +
    '>Morning brief</a><a class="tab" href="/schedule.html">Schedule</a></div></div>', true);
  document.body.insertBefore(nav, document.body.firstChild);
  fetch('/schedule.json', { cache: 'no-store' }).then(r => r.ok ? r.json() : Promise.reject()).then(data => {
    setData(data);
    const today = todayBkk(), tomorrow = addDays(today, 1);
    let rows = stripDay(today, 'Today') + stripDay(tomorrow, 'Tomorrow');
    if (!summary(BY[tomorrow])) {
      let n = addDays(tomorrow, 1), i = 0;
      while (i < 14 && !summary(BY[n])) { n = addDays(n, 1); i++; }
      if (summary(BY[n])) rows += stripDay(n, 'Next class day');
    }
    const strip = host('<div class="strip sd"><div class="wrap">' + rows + '<a class="more" href="/schedule.html">Full schedule →</a></div></div>', false);
    nav.after(strip);
  }).catch(() => { /* no data: just keep the tab bar */ });
})();
