/* Class-schedule tabs - owned by Claude, generated by schedule/sync_schedule.py.
   Adds a "Morning brief | Schedule" tab bar and a today/tomorrow strip to any page
   that includes <script src="/tabs.js" defer></script>. It never edits that page's
   files: everything is inserted in the browser, inside shadow DOM. */
(function () {
  if (window.__sdTabs) return;
  window.__sdTabs = true;
/*__CORE__*/
  const CSS = `/*__CSS__*/
.wrap{max-width:42rem;margin:0 auto;padding:.5rem 1.25rem}
.nav{background:var(--bg,#0f1115);border-bottom:1px solid var(--sd-line);font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
.nav .wrap{display:flex;gap:.5rem}
.tab{flex:1;text-align:center;padding:.6rem .8rem;border-radius:12px;text-decoration:none;font-weight:600;font-size:.95rem;color:var(--sd-text);border:1px solid var(--sd-line)}
.tab[aria-current="page"]{background:color-mix(in srgb,var(--sd-accent) 18%,transparent);border-color:var(--sd-accent)}
.strip{font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;font-size:.92rem}
.strip .wrap{padding-top:.9rem;padding-bottom:.2rem}
.sd-sd{display:flex;flex-wrap:wrap;align-items:center;gap:.3rem .6rem;margin-top:.55rem}
.sd-sd .sd-chip{font-size:.72rem;min-width:2.6rem}
.sd-times b{font-variant-numeric:tabular-nums}
.sd-rest-i{color:var(--sd-muted)}
.strip .sd-mini{margin:.15rem 0 0 .2rem}
.more{display:inline-block;margin-top:.7rem;color:var(--link,#7db4ff);font-size:.85rem}
`;
  const here = location.pathname.replace(/index\.html$/, '') || '/';
  function host(html, sticky) {
    const h = document.createElement('div');
    h.className = 'sd-host';
    if (sticky) h.style.cssText = 'position:sticky;top:0;z-index:50';
    const root = h.attachShadow({ mode: 'open' });
    root.innerHTML = '<style>' + CSS + '</style>' + html;
    return h;
  }
  function stripDay(ds, rel) {
    const day = BY[ds], s = summary(day), ev = eventsFor(ds);
    let h = '<div class="sd-sd">' + chip(ds) + '<span><b>' + rel + '</b> · ' + shortDate(ds) + '</span>';
    if (s && s.office) h += '<span class="sd-times">⏰ <b>' + f12(s.start) + '</b> start · Office · ⏰ <b>' + f12(s.fin) + '</b> finish</span>';
    else if (s) h += '<span class="sd-times">⏰ <b>' + f12(s.start) + '</b> start · ' + f12(s.first) + ' first class · ⏰ <b>' + f12(s.fin) + '</b> finish</span>';
    else h += '<span class="sd-rest-i">' + (day ? 'Free day' : 'not in the schedule yet') + '</span>';
    h += '</div>';
    const items = (s && !s.office ? day.classes.map(miniItem) : []).concat(ev.map(miniEvent));
    if (items.length) h += '<ul class="sd-mini">' + items.join('') + '</ul>';
    return h;
  }
  const navHTML = tabs => '<div class="nav sd"><div class="wrap">' + tabsHTML(tabs, here, 'tab') + '</div></div>';
  const nav = host(navHTML(TABS.filter(t => !t.optional)), true);
  document.body.insertBefore(nav, document.body.firstChild);
  // On the brief page (an <article> with <h2> sections), also load the dashboard layer.
  if (document.querySelector('article h2') && !/\/(schedule|studio)\.html$/.test(location.pathname)) {
    const bf = document.createElement('script'); bf.src = '/brief.js'; bf.defer = true; document.head.appendChild(bf);
  }
  visibleTabs().then(tabs => { nav.shadowRoot.innerHTML = '<style>' + CSS + '</style>' + navHTML(tabs); });
  Promise.all([fetch('/schedule.json', { cache: 'no-store' }).then(r => r.ok ? r.json() : Promise.reject()), loadEvents()]).then(res => {
    setData(res[0]);
    const today = todayBkk(), tomorrow = addDays(today, 1);
    let rows = stripDay(today, 'Today') + stripDay(tomorrow, 'Tomorrow');
    if (!summary(BY[tomorrow])) {
      let n = addDays(tomorrow, 1), i = 0;
      while (i < 14 && !summary(BY[n])) { n = addDays(n, 1); i++; }
      if (summary(BY[n])) rows += stripDay(n, 'Next work day');
    }
    const strip = host('<div class="strip sd"><div class="wrap">' + rows + '<a class="more" href="/schedule.html">Full schedule →</a></div></div>', false);
    nav.after(strip);
  }).catch(() => { /* no data: just keep the tab bar */ });
})();
